sudo: required
services:
  - docker

before_install:
  - docker build -t dreamzoner/docker-react -f Dockerfile.dev .

script:
  - docker run dreamzoner/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker2'
  env: 'Docker2-env'
  bucket_name: 'elasticbeanstalk-us-west-1-169988050228'
  bucket_path: 'docker2'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
